/*
===============================================================================
 Project: Uber Operations & Revenue Analysis
 File: 03_kpis.sql
 Author: Christian Mederos

 Description:
 This script answers key business questions by calculating performance
 indicators related to revenue, fares, payment methods, cities, zones,
 and driver performance.
===============================================================================
*/

USE uber;
/*
===============================================================================
F1. TOTAL REVENUES BY CITY
===============================================================================

Question:
What are the total revenues by city?

Business Purpose:
Measure the revenue generated by each city to identify the strongest
markets and support strategic business decisions.
===============================================================================
*/

SELECT
    l.city,
    ROUND(SUM(t.total_fare), 0) AS total_revenue
FROM locations AS l
JOIN trips AS t
    ON l.location_id = t.pickup_location_id
GROUP BY l.city
ORDER BY total_revenue DESC;

/*
Observation:

- Houston generates the highest total revenue, reaching 224,894 monetary units.
- Los Angeles ranks second with 190,567, followed by New York with 166,762
  and Chicago with 137,943.
- Revenue is not evenly distributed across cities, with Houston clearly
  outperforming the remaining markets.
- These results identify Houston as the strongest revenue-generating city
  in the dataset and provide a baseline for further financial analysis.
*/

