/*
===============================================================================
 Project: Uber Operations & Revenue Analysis
 File: 03_kpis.sql
 Author: Christian Mederos

 Description:
 This script calculates the key performance indicators required to evaluate
 the financial, operational, driver, rider, cancellation, and service quality
 performance of the Uber platform.

 These KPIs provide the quantitative foundation for answering the business
 questions defined in the project and for building the Power BI dashboards.
===============================================================================
*/

USE uber;
/*
===============================================================================
F1. TOTAL REVENUES BY CITY
===============================================================================

Question:
What are the total revenues by city?

Business Purpose:
Measure the revenue generated by each city to identify the strongest
markets and support strategic business decisions.
===============================================================================
*/

SELECT
    l.city,
    ROUND(SUM(t.total_fare), 0) AS total_revenue
FROM locations AS l
JOIN trips AS t
    ON l.location_id = t.pickup_location_id
GROUP BY l.city
ORDER BY total_revenue DESC;

/*
Observation:

- Houston generates the highest total revenue, reaching 224,894 monetary units.
- Los Angeles ranks second with 190,567, followed by New York with 166,762
  and Chicago with 137,943.
- Revenue is not evenly distributed across cities, with Houston clearly
  outperforming the remaining markets.
- These results identify Houston as the strongest revenue-generating city
  in the dataset and provide a baseline for further financial analysis.
*/
/*
===============================================================================
F2. TOTAL REVENUES BY ZONE
===============================================================================

Question:
What are the total revenues by zone?

Business Purpose:
Measure the revenue generated by each pickup zone to identify the
highest-performing areas and support geographic business decisions.
===============================================================================
*/

SELECT
    l.zone_name,
    ROUND(SUM(t.total_fare), 0) AS total_revenue
FROM locations AS l
JOIN trips AS t
    ON l.location_id = t.pickup_location_id
GROUP BY l.zone_name
ORDER BY total_revenue DESC;

/*
Observation:

- IAH Airport generates the highest total revenue, reaching 34,881 monetary
  units, followed by Sugar Land (32,425) and JFK Airport (29,492).
- Airport locations dominate the top revenue-generating zones, with IAH,
  JFK, Hobby Airport, O'Hare Airport, LaGuardia Airport, LAX Airport, and
  Midway Airport all appearing among the highest-performing areas.
- Several commercial and residential zones, such as Sugar Land, Energy
  Corridor, and Compton, also contribute significantly to total revenue.
- These findings indicate that transportation hubs and high-demand urban
  areas are the primary revenue drivers within the platform.
*/
/*
===============================================================================
F3. AVERAGE FARE BY CITY
===============================================================================

Question:
What is the average fare by city?

Business Purpose:
Analyze the average fare generated in each city to compare pricing
patterns and identify differences in trip value across markets.
===============================================================================
*/

SELECT
    l.city,
    ROUND(AVG(t.total_fare), 2) AS avg_fare
FROM locations AS l
JOIN trips AS t
    ON l.location_id = t.pickup_location_id
GROUP BY l.city
ORDER BY avg_fare DESC;

/*
Observation:

- Los Angeles has the highest average fare at 44.48 monetary units, followed
  by Houston with an average fare of 42.20.
- Chicago and New York have considerably lower average fares, with averages
  of 29.39 and 29.29, respectively.
- Although Houston generates the highest total revenue, Los Angeles records
  the highest average fare, indicating that higher revenue is influenced by
  both trip volume and fare value.
- Comparing average fares across cities provides valuable insight into
  pricing patterns and market performance.
*/
/*
===============================================================================
F4. AVERAGE FARE BY DRIVER
===============================================================================

Question:
What is the average fare by driver?

Business Purpose:
Evaluate the average fare generated by each driver to identify differences
in trip value and support driver performance analysis.
===============================================================================
*/

SELECT
    d.driver_id,
    ROUND(AVG(t.total_fare), 2) AS avg_fare
FROM drivers AS d
JOIN trips AS t
    ON d.driver_id = t.driver_id
GROUP BY d.driver_id
ORDER BY avg_fare DESC, d.driver_id;

/*
Observation:

- Driver 241 records the highest average fare at 55.28 monetary units,
  followed by Driver 84 (52.18) and Driver 266 (52.05).
- The top-performing drivers consistently achieve average fares above
  50 monetary units per trip.
- Differences in average fare may be influenced by factors such as trip
  distance, operating area, or service demand.
- This analysis helps identify drivers associated with higher-value trips
  and provides a foundation for further performance evaluation.
*/
/*
===============================================================================
F5. CITIES WITH REVENUE ABOVE THE OVERALL AVERAGE
===============================================================================

Question:
Which cities generate revenue above the overall average?

Business Purpose:
Identify cities whose total revenue exceeds the average revenue across all
cities, highlighting the strongest-performing markets.
===============================================================================
*/

WITH city_revenue AS (
    SELECT
        l.city,
        SUM(t.total_fare) AS total_revenue
    FROM locations AS l
    JOIN trips AS t
        ON l.location_id = t.pickup_location_id
    GROUP BY l.city
)

SELECT
    city,
    ROUND(total_revenue, 0) AS total_revenue
FROM city_revenue
WHERE total_revenue > (
    SELECT AVG(total_revenue)
    FROM city_revenue
)
ORDER BY total_revenue DESC;

/*
Observation:

- Only Houston and Los Angeles generate total revenue above the overall
  average revenue across all cities.
- Houston remains the strongest-performing market, followed by
  Los Angeles.
- The results indicate that revenue generation is concentrated in a small
  number of cities, while the remaining markets perform below the overall
  average.
- Identifying cities that outperform the average helps prioritize strategic
  investments and supports data-driven business decisions.
*/
/*
===============================================================================
F6. THREE BUSIEST ZONES WITHIN EACH CITY
===============================================================================

Question:
Which are the three busiest zones within each city?

Business Purpose:
Identify the highest-demand pickup zones within each city to support driver
allocation, demand management, and operational planning.
===============================================================================
*/

WITH zone_ranking AS (
    SELECT
        l.city,
        l.zone_name,
        COUNT(t.trip_id) AS trip_count,
        DENSE_RANK() OVER (
            PARTITION BY l.city
            ORDER BY COUNT(t.trip_id) DESC
        ) AS zone_rank
    FROM locations AS l
    JOIN trips AS t
        ON l.location_id = t.pickup_location_id
    GROUP BY
        l.city,
        l.zone_name
)

SELECT
    city,
    zone_name,
    trip_count,
    zone_rank
FROM zone_ranking
WHERE zone_rank <= 3
ORDER BY
    city,
    zone_rank,
    trip_count DESC;

/*
Observation:

- The analysis identifies the busiest pickup zones within each city based
  on trip volume.
- New York records the highest demand, with Flushing leading all zones at
  607 trips.
- Chicago and New York include ties in the rankings, resulting in more than
  three zones being returned because DENSE_RANK() assigns the same rank to
  zones with an equal number of trips.
- These results help identify high-demand areas and can support decisions
  related to driver allocation and operational planning.
*/
/*
===============================================================================
F7. REVENUE RANKING BY CITY
===============================================================================

Question:
What is the revenue ranking by city?

Business Purpose:
Rank cities based on total revenue to identify the strongest-performing
markets and support strategic business decisions.
===============================================================================
*/

SELECT
    l.city,
    ROUND(SUM(t.total_fare), 0) AS total_revenue,
    DENSE_RANK() OVER (
        ORDER BY SUM(t.total_fare) DESC
    ) AS revenue_rank
FROM locations AS l
JOIN trips AS t
    ON l.location_id = t.pickup_location_id
GROUP BY l.city
ORDER BY revenue_rank;

/*
Observation:

- Houston ranks first in total revenue with 224,894 monetary units,
  followed by Los Angeles (190,567), New York (166,762), and Chicago
  (137,943).
- No ties are present in the revenue ranking, resulting in a unique
  position for each city.
- The ranking confirms Houston as the highest-performing market in terms
  of revenue generation, while Chicago records the lowest revenue among
  the four cities.
- Revenue rankings provide a clear comparison of market performance and
  support strategic resource allocation across cities.
*/
/*
===============================================================================
F8. TRIP VOLUME RANKING BY ZONE WITHIN EACH CITY
===============================================================================

Question:
What is the trip volume ranking by zone within each city?

Business Purpose:
Rank all pickup zones within each city according to trip volume to identify
high-demand and low-demand areas, supporting operational planning and
resource allocation.
===============================================================================
*/

WITH zone_ranking AS (
    SELECT
        l.city,
        l.zone_name,
        COUNT(t.trip_id) AS trip_count,
        DENSE_RANK() OVER (
            PARTITION BY l.city
            ORDER BY COUNT(t.trip_id) DESC
        ) AS zone_rank
    FROM locations AS l
    JOIN trips AS t
        ON l.location_id = t.pickup_location_id
    GROUP BY
        l.city,
        l.zone_name
)

SELECT
    city,
    zone_name,
    trip_count,
    zone_rank
FROM zone_ranking
ORDER BY
    city,
    zone_rank,
    trip_count DESC;

/*
Observation:

- The ranking provides a complete view of trip demand across all pickup
  zones within each city.
- Flushing is the busiest zone overall with 607 trips, while Downtown
  Houston leads Houston with 568 trips, Compton leads Los Angeles with
  450 trips, and Navy Pier leads Chicago with 494 trips.
- Several cities contain ties in the ranking. For example, Midway Airport
  and Union Station share second place in Chicago, while Upper West Side
  and Greenwich Village share second place in New York.
- Ranking zones by trip volume helps identify areas with consistently high
  demand and supports operational decisions such as driver allocation and
  service optimization.
*/
/*
===============================================================================
F9. PAYMENT METHODS WITH THE HIGHEST PERCENTAGE OF TRIPS
===============================================================================

Question:
Which payment methods generate the highest percentage of trips?

Business Purpose:
Analyze the distribution of payment methods to understand customer payment
preferences and support payment strategy decisions.
===============================================================================
*/

SELECT
    method,
    COUNT(*) AS payment_count,
    ROUND(
        COUNT(*) * 100.0 / SUM(COUNT(*)) OVER (),
        2
    ) AS percentage
FROM payments
GROUP BY method
ORDER BY payment_count DESC;

/*
Observation:

- Card is the most frequently used payment method, accounting for 33.87%
  of all trips.
- Wallet follows closely with 33.40%, while Cash represents 32.72% of all
  trips.
- The distribution of payment methods is remarkably balanced, with each
  method contributing approximately one-third of all transactions.
- This balanced distribution suggests that customers are comfortable using
  multiple payment options, reducing dependency on a single payment method.
*/
