/*
===============================================================================
UBER OPERATIONS & REVENUE ANALYSIS
DASHBOARD DATASETS
===============================================================================

Purpose:
Prepare aggregated datasets for Power BI visualizations.

The queries in this file generate the data used to build the interactive
dashboard. Each query corresponds to a specific visual or KPI and can be
exported as a CSV file for use in Power BI.

===============================================================================
*/
/*
===============================================================================
DATASET 1 - EXECUTIVE SUMMARY
===============================================================================

Purpose:
Provide the main KPI values displayed in the Executive Overview page of the
Power BI dashboard.

Dashboard Visual:
KPI Cards

Output:
- Total Revenue
- Completed Trips
- Average Fare
- Cancellation Rate
- Average Driver Rating

CSV File:
executive_summary.csv
===============================================================================
*/

SELECT
    ROUND(
        SUM(CASE
            WHEN status = 'completed' THEN total_fare
            ELSE 0
        END),
        2
    ) AS total_revenue,

    COUNT(CASE
        WHEN status = 'completed' THEN trip_id
    END) AS completed_trips,

    ROUND(
        AVG(CASE
            WHEN status = 'completed' THEN total_fare
        END),
        2
    ) AS average_fare,

    ROUND(
        COUNT(CASE
            WHEN status = 'cancelled' THEN trip_id
        END) * 100.0 / COUNT(trip_id),
        2
    ) AS cancellation_rate,

    ROUND(
        (SELECT AVG(rating)
        FROM drivers),
        2
    ) AS average_driver_rating
FROM trips;

/*
===============================================================================
DATASET 2 - REVENUE BY CITY
===============================================================================

Purpose:
Compare total revenue generated across cities and identify the strongest
financial markets.

Dashboard Visual:
Clustered Bar Chart

Output:
- City
- Total Revenue

CSV File:
revenue_by_city.csv
===============================================================================
*/

SELECT
    l.city,
    ROUND(SUM(t.total_fare), 2) AS total_revenue
FROM trips AS t
JOIN locations AS l
    ON t.pickup_location_id = l.location_id
WHERE t.status = 'completed'
GROUP BY
    l.city
ORDER BY
    total_revenue DESC;
/*
===============================================================================
DATASET 3 - COMPLETED TRIPS BY CITY
===============================================================================

Purpose:
Compare the number of completed trips across cities to identify the markets
with the highest operational activity.

Dashboard Visual:
Clustered Column Chart

Output:
- City
- Completed Trips

CSV File:
completed_trips_by_city.csv
===============================================================================
*/

SELECT
    l.city,
    COUNT(t.trip_id) AS completed_trips
FROM trips AS t
JOIN locations AS l
    ON t.pickup_location_id = l.location_id
WHERE t.status = 'completed'
GROUP BY
    l.city
ORDER BY
    completed_trips DESC;
/*
===============================================================================
DATASET 4 - PAYMENT METHODS
===============================================================================

Purpose:
Analyze the distribution of payment methods used by riders to understand
customer payment preferences.

Dashboard Visual:
Donut Chart

Output:
- Payment Method
- Total Payments

CSV File:
payment_methods.csv
===============================================================================
*/

SELECT
    method AS payment_method,
    COUNT(payment_id) AS total_payments
FROM payments
GROUP BY
    method
ORDER BY
    total_payments DESC;
/*
===============================================================================
DATASET 5 - PEAK DEMAND HOURS
===============================================================================

Purpose:
Identify the hours with the highest trip demand to support driver allocation,
shift planning, and operational efficiency.

Dashboard Visual:
Clustered Column Chart

Output:
- Hour of Day
- Total Trips

CSV File:
peak_demand_hours.csv
===============================================================================
*/

SELECT
    HOUR(requested_at) AS hour_of_day,
    COUNT(trip_id) AS total_trips
FROM trips
GROUP BY
    hour_of_day
ORDER BY
    hour_of_day;
/*
===============================================================================
DATASET 6 - DRIVER REVENUE
===============================================================================

Purpose:
Compare total revenue generated by drivers and identify the platform's
highest financial contributors.

Dashboard Visual:
Horizontal Bar Chart

Output:
- Driver ID
- Total Revenue

CSV File:
driver_revenue.csv
===============================================================================
*/

SELECT
    driver_id,
    ROUND(SUM(total_fare), 2) AS total_revenue
FROM trips
WHERE status = 'completed'
GROUP BY
    driver_id
ORDER BY
    total_revenue DESC;
/*
===============================================================================
DATASET 7 - DRIVER RATING VS REVENUE
===============================================================================

Purpose:
Analyze the relationship between driver ratings and total revenue to evaluate
whether higher service quality is associated with stronger financial
performance.

Dashboard Visual:
Scatter Chart

Output:
- Driver ID
- Driver Rating
- Total Revenue

CSV File:
driver_rating_vs_revenue.csv
===============================================================================
*/

SELECT
    d.driver_id,
    d.rating AS driver_rating,
    ROUND(SUM(t.total_fare), 2) AS total_revenue
FROM drivers AS d
JOIN trips AS t
    ON d.driver_id = t.driver_id
WHERE t.status = 'completed'
GROUP BY
    d.driver_id,
    d.rating
ORDER BY
    total_revenue DESC;
/*
===============================================================================
DATASET 8 - TOP REVENUE RIDERS
===============================================================================

Purpose:
Identify the riders who generate the highest revenue to understand customer
value and support loyalty and retention strategies.

Dashboard Visual:
Horizontal Bar Chart

Output:
- Rider ID
- Total Revenue

CSV File:
top_revenue_riders.csv
===============================================================================
*/

SELECT
    rider_id,
    ROUND(SUM(total_fare), 2) AS total_revenue
FROM trips
WHERE status = 'completed'
GROUP BY
    rider_id
ORDER BY
    total_revenue DESC;
/*
===============================================================================
DATASET 9 - AVERAGE TRIP DURATION BY CITY
===============================================================================

Purpose:
Compare the average duration of completed trips across cities to identify
differences in travel patterns and operational efficiency.

Dashboard Visual:
Clustered Column Chart

Output:
- City
- Average Trip Duration (Minutes)

CSV File:
trip_duration_by_city.csv
===============================================================================
*/

SELECT
    l.city,
    ROUND(AVG(t.duration_mins), 2) AS average_trip_duration
FROM trips AS t
JOIN locations AS l
    ON t.pickup_location_id = l.location_id
WHERE t.status = 'completed'
GROUP BY
    l.city
ORDER BY
    average_trip_duration DESC;
/*
===============================================================================
DATASET 10 - HIGH DEMAND ZONES
===============================================================================

Purpose:
Identify the pickup zones with the highest trip demand to support driver
allocation and improve operational planning.

Dashboard Visual:
Horizontal Bar Chart

Output:
- Zone Name
- Completed Trips

CSV File:
high_demand_zones.csv
===============================================================================
*/

SELECT
    l.zone_name,
    COUNT(t.trip_id) AS completed_trips
FROM trips AS t
JOIN locations AS l
    ON t.pickup_location_id = l.location_id
WHERE t.status = 'completed'
GROUP BY
    l.zone_name
ORDER BY
    completed_trips DESC;
/*
===============================================================================
DATASET 11 - CANCELLATION RATE BY CITY
===============================================================================

Purpose:
Compare cancellation rates across cities to identify locations with the
greatest operational challenges and opportunities for service improvement.

Dashboard Visual:
Clustered Column Chart

Output:
- City
- Cancellation Rate (%)

CSV File:
cancellation_rate_by_city.csv
===============================================================================
*/

SELECT
    l.city,
    ROUND(
        COUNT(CASE
            WHEN t.status = 'cancelled' THEN t.trip_id
        END) * 100.0 /
        COUNT(t.trip_id),
        2
    ) AS cancellation_rate
FROM trips AS t
JOIN locations AS l
    ON t.pickup_location_id = l.location_id
GROUP BY
    l.city
ORDER BY
    cancellation_rate DESC;
/*
===============================================================================
DATASET 12 - SURGE PRICING VS CANCELLATION RATE
===============================================================================

Purpose:
Evaluate whether higher surge pricing levels are associated with increased
trip cancellation rates.

Dashboard Visual:
Clustered Column Chart

Output:
- Surge Level
- Cancellation Rate (%)

CSV File:
surge_vs_cancellation.csv
===============================================================================
*/

SELECT
    CASE
        WHEN surge_multiplier = 1 THEN 'No Surge'
        WHEN surge_multiplier < 2 THEN 'Low Surge'
        ELSE 'High Surge'
    END AS surge_level,

    ROUND(
        COUNT(CASE
            WHEN status = 'cancelled' THEN trip_id
        END) * 100.0 /
        COUNT(trip_id),
        2
    ) AS cancellation_rate
FROM trips
GROUP BY
    surge_level
ORDER BY
    cancellation_rate DESC;
